server:
  port: 8888
  
spring:
  kafka:
    producer:
      bootstrap-servers: <host>:<port>
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  twitter:
    consumer-key: <consumer-key>
    consumer-secret: <consumer-secret>
    access-token: <access-token>
    token-secret: <token-secret>
    hashtag: <hashtag>
  